blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/adamralph/.github/blob/master/.github/SUPPORT.md
    about: Instructions for getting support. Please ask and answer questions here.
